package com.example.karanc.buttler.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.PrimaryKey;
import android.support.annotation.Nullable;

import java.io.Serializable;

import static com.example.karanc.buttler.appUtils.Utils.TABLE_NAME;

/**
 * Entity mapped to table "NOTE".
 */
@Entity(tableName = TABLE_NAME)
public class Note implements Serializable {

    private int Color;

    @PrimaryKey(autoGenerate = true)
    private long id;
    /**
     * Not-null value.
     */

    private String Desc;
    private String Time;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Note() {
    }


    public Note(String Desc, String Time) {
        this.Desc = Desc;
        this.Time = Time;
    }

    public int getColor() {
        return Color;
    }

    public void setColor(int color) {
        Color = color;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getDesc() {
        return Desc;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setDesc(String Desc) {
        this.Desc = Desc;
    }

    public String getTime() {
        return Time;
    }

    public void setTime(String Time) {
        this.Time = Time;
    }


    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
